version: "3.7"

services:
    node:
        container_name: node
        image: node:alpine3.17
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html

    go:
        container_name: go
        image: golang:1.20-rc-alpine
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html

    php:
        container_name: php
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html